### ISSUE TITLE
CI FAILURE: Builds broken due to missing PIP dependency

### ISSUE THREAD

**Issue by gus33000** [edk2-porting/MU-SM8150Pkg#433]
https://github.com/Project-Aloha/mu_aloha_platforms/actions/runs/12333307372

```
Defaulting to user installation because normal site-packages is not writeable
Collecting edk2-pytool-library==0.21.11
  Downloading edk2_pytool_library-0.21.11-py3-none-any.whl (417 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.7/417.7 KB 16.4 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement edk2-pytool-extensions==0.28.0 (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.13.10, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.14.5, 0.14.6, 0.15.0, 0.15.2, 0.16.0, 0.17.0, 0.17.1, 0.17.2, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.20.0, 0.20.1, 0.21.0, 0.21.1, 0.21.2, 0.21.5, 0.21.6, 0.21.7, 0.21.8, 0.21.9, 0.21.11, 0.22.0, 0.22.1, 0.22.2, 0.23.0, 0.23.2, 0.23.3, 0.23.4, 0.23.5, 0.23.6, 0.23.7, 0.23.8, 0.23.9, 0.23.10, 0.24.0, 0.24.1, 0.25.0, 0.25.1, 0.26.0, 0.26.1, 0.26.2, 0.26.3, 0.26.4, 0.27.0, 0.27.1, 0.27.2, 0.27.3, 0.27.4, 0.27.5, 0.27.6, 0.27.8, 0.27.9, 0.27.10, 0.27.11, 0.27.12)
ERROR: No matching distribution found for edk2-pytool-extensions==0.28.0
Traceback (most recent call last):
  File "/home/runner/work/mu_aloha_platforms/mu_aloha_platforms/./build_uefi.py", line 15, in <module>
    import Levenshtein
ModuleNotFoundError: No module named 'Levenshtein'
```

https://github.com/Project-Aloha/mu_aloha_platforms/actions/runs/12333308016

```
Defaulting to user installation because normal site-packages is not writeable
Collecting edk2-pytool-library==0.21.11
  Downloading edk2_pytool_library-0.21.11-py3-none-any.whl (417 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.7/417.7 KB 6.6 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement edk2-pytool-extensions==0.28.0 (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.13.10, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.14.5, 0.14.6, 0.15.0, 0.15.2, 0.16.0, 0.17.0, 0.17.1, 0.17.2, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.20.0, 0.20.1, 0.21.0, 0.21.1, 0.21.2, 0.21.5, 0.21.6, 0.21.7, 0.21.8, 0.21.9, 0.21.11, 0.22.0, 0.22.1, 0.22.2, 0.23.0, 0.23.2, 0.23.3, 0.23.4, 0.23.5, 0.23.6, 0.23.7, 0.23.8, 0.23.9, 0.23.10, 0.24.0, 0.24.1, 0.25.0, 0.25.1, 0.26.0, 0.26.1, 0.26.2, 0.26.3, 0.26.4, 0.27.0, 0.27.1, 0.27.2, 0.27.3, 0.27.4, 0.27.5, 0.27.6, 0.27.8, 0.27.9, 0.27.10, 0.27.11, 0.27.12)
ERROR: No matching distribution found for edk2-pytool-extensions==0.28.0
Traceback (most recent call last):
  File "/home/runner/work/mu_aloha_platforms/mu_aloha_platforms/./build_uefi.py", line 15, in <module>
    import Levenshtein
ModuleNotFoundError: No module named 'Levenshtein'
```

https://github.com/Project-Aloha/mu_aloha_platforms/actions/runs/12333308737

```
Defaulting to user installation because normal site-packages is not writeable
Collecting edk2-pytool-library==0.21.11
  Downloading edk2_pytool_library-0.21.11-py3-none-any.whl (417 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.7/417.7 KB 9.9 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement edk2-pytool-extensions==0.28.0 (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.13.10, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.14.5, 0.14.6, 0.15.0, 0.15.2, 0.16.0, 0.17.0, 0.17.1, 0.17.2, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.20.0, 0.20.1, 0.21.0, 0.21.1, 0.21.2, 0.21.5, 0.21.6, 0.21.7, 0.21.8, 0.21.9, 0.21.11, 0.22.0, 0.22.1, 0.22.2, 0.23.0, 0.23.2, 0.23.3, 0.23.4, 0.23.5, 0.23.6, 0.23.7, 0.23.8, 0.23.9, 0.23.10, 0.24.0, 0.24.1, 0.25.0, 0.25.1, 0.26.0, 0.26.1, 0.26.2, 0.26.3, 0.26.4, 0.27.0, 0.27.1, 0.27.2, 0.27.3, 0.27.4, 0.27.5, 0.27.6, 0.27.8, 0.27.9, 0.27.10, 0.27.11, 0.27.12)
ERROR: No matching distribution found for edk2-pytool-extensions==0.28.0
Traceback (most recent call last):
  File "/home/runner/work/mu_aloha_platforms/mu_aloha_platforms/./build_uefi.py", line 15, in <module>
    import Levenshtein
ModuleNotFoundError: No module named 'Levenshtein'
```

https://github.com/Project-Aloha/mu_aloha_platforms/actions/runs/12333309413

```
Defaulting to user installation because normal site-packages is not writeable
Collecting edk2-pytool-library==0.21.11
  Downloading edk2_pytool_library-0.21.11-py3-none-any.whl (417 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.7/417.7 KB 9.1 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement edk2-pytool-extensions==0.28.0 (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.13.10, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.14.5, 0.14.6, 0.15.0, 0.15.2, 0.16.0, 0.17.0, 0.17.1, 0.17.2, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.20.0, 0.20.1, 0.21.0, 0.21.1, 0.21.2, 0.21.5, 0.21.6, 0.21.7, 0.21.8, 0.21.9, 0.21.11, 0.22.0, 0.22.1, 0.22.2, 0.23.0, 0.23.2, 0.23.3, 0.23.4, 0.23.5, 0.23.6, 0.23.7, 0.23.8, 0.23.9, 0.23.10, 0.24.0, 0.24.1, 0.25.0, 0.25.1, 0.26.0, 0.26.1, 0.26.2, 0.26.3, 0.26.4, 0.27.0, 0.27.1, 0.27.2, 0.27.3, 0.27.4, 0.27.5, 0.27.6, 0.27.8, 0.27.9, 0.27.10, 0.27.11, 0.27.12)
ERROR: No matching distribution found for edk2-pytool-extensions==0.28.0
Traceback (most recent call last):
  File "/home/runner/work/mu_aloha_platforms/mu_aloha_platforms/./build_uefi.py", line 15, in <module>
    import Levenshtein
ModuleNotFoundError: No module named 'Levenshtein'
```

**Comment by sunflower2333** [comment]
fixed in this commit https://github.com/Project-Aloha/mu_aloha_platforms/commit/be289e7157a0a598d95608e2e879fe8e346b8139
